// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAUPHAnF8ymf_i7jnVRIBeloKJASS4oeI',
    appId: '1:1088775137967:web:5fa7e00396409abdde025a',
    messagingSenderId: '1088775137967',
    projectId: 'socialmediaapp-a7d06',
    authDomain: 'socialmediaapp-a7d06.firebaseapp.com',
    storageBucket: 'socialmediaapp-a7d06.firebasestorage.app',
    measurementId: 'G-JSDDFCZDW2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCAUPHAnF8ymf_i7jnVRIBeloKJASS4oeI',
    appId: '1:1088775137967:web:200e51fa96f1bba6de025a',
    messagingSenderId: '1088775137967',
    projectId: 'socialmediaapp-a7d06',
    authDomain: 'socialmediaapp-a7d06.firebaseapp.com',
    storageBucket: 'socialmediaapp-a7d06.firebasestorage.app',
    measurementId: 'G-9K9J0J4W5S',
  );
}
